#!/usr/bin/python3

import sys
import subprocess
import argparse
import printfile.printfile as printfile

root_parser = argparse.ArgumentParser(prog="pt", description="CLI for the UCF Programming Team")
root_parser.add_argument("--override", action="store_true", help="Override checks like the 'During Practice' check")
subparsers = root_parser.add_subparsers(title="Commands", dest='pt_subcommand')

# printfile_parser = subparsers.add_parser("printfile", help="Formats and prints a source file")
# printfile_parser.add_argument("FILE", help="The source file to print")

printfile.attach_parser(subparsers)

minecraft_parser = subparsers.add_parser("minecraft", help="Run minecraft!")


args = root_parser.parse_args()

if args.pt_subcommand == 'printfile':
    printfile.exec(args)
else:
    print(args)
