#!/usr/bin/python3

import argparse
import printfile.printfile as printfile

root_parser = argparse.ArgumentParser(prog="pt", description="CLI for the UCF Programming Team")
root_parser.add_argument("--override", action="store_true", help="Override checks like the 'During Practice' check")
subparsers = root_parser.add_subparsers(title="Commands", dest='pt_subcommand')

# Attach all the parsers
printfile.attach_parser(subparsers)

# Parse args
args = root_parser.parse_args()

# Run commands that don't need override
if args.pt_subcommand == 'printfile':
    printfile.exec(args)
    exit(0)

# TODO
print(args)
